#!/bin/bash
python from_bed_to_BAM_for_chicago.py /home/travis/build/pabloacera/C-HiC/tests/data/test_fastq2bed/03_filtered_reads/valid_r1-r2_intersection_b51cdf1282.tsv 2 /home/travis/build/pabloacera/C-HiC/tests/data/test_bed2bam/outbam
